/* ─── YOUR ORIGINAL PROJECT DATA ─────────────────────────────────────────── */
export const RAW_PROJECTS = [
  {
    title: "Kenyan Real Estate Website",
    type: "Web Application",
    description:
      "Full-stack real estate platform connecting clients, landlords, and administrators through property listings, real-time messaging, and payment processing. Features role-based dashboards, Google Maps integration, M-Pesa payments, and comprehensive property management with secure JWT authentication.",
    tech: [
      "React",
      "Node.js",
      "MongoDB",
      "Socket.IO",
      "M-Pesa API",
      "Cloudinary",
    ],
    features: [
      "Property Management – Complete CRUD operations for listings",
      "Real-time chat between clients and landlords (Socket.IO)",
      "Google Maps integration for property location",
      "M-Pesa payment processing for landlord subscriptions",
      "Role-based dashboards (Client, Landlord, Admin)",
      "Media uploads (images/videos) via Cloudinary",
      "Review and rating system for properties",
    ],
    sector: "Real Estate",
  },
  {
    title: "Xgene Labs - Molecular Diagnostics Website",
    type: "Corporate Website",
    description:
      "Professional website for Xgene Labs, a clinical-grade molecular diagnostics company in Kenya. Showcases genetic testing services, diagnostic kits, medical equipment, and transparent prepaid testing programs with M-Pesa integration.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "shadcn/ui",
      "Vite",
      "Vercel",
    ],
    features: [
      "Service showcase – genetic testing, diagnostic kits, medical equipment",
      "Prepaid testing program with M-Pesa tokens for healthcare facilities",
      "Clear pricing and target audience segmentation (patients, clinics, hospitals)",
      "Mobile-responsive, trust‑focused UI",
      "Smooth animations with Framer Motion",
    ],
    sector: "Healthcare",
  },
  {
    title: "Siprosa Foundation - Educational Non-Profit Website",
    type: "Non-Profit Website",
    description:
      "Website for Siprosa Foundation, a non-profit transforming education in Kenya through 'Futures Green Schools' – focusing on early childhood education, environmental stewardship, and holistic child development.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "shadcn/ui",
      "Vite",
      "Vercel",
    ],
    features: [
      "Mission & values communication",
      "Futures Green Schools model showcase",
      "Founder story (Dr. Mary Otieno)",
      "Call‑to‑action for donations, partnerships, volunteering",
      "Fully responsive and emotionally engaging design",
    ],
    sector: "Education / Non-Profit",
  },
  {
    title: "Somanasi - Tech Training & Solutions Company",
    type: "Corporate Website",
    description:
      "Corporate website for Somanasi, a Kenyan tech training and solutions provider offering courses in AI, software development, data analytics, and cybersecurity, plus custom AI agents and chatbots.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "shadcn/ui",
      "Vite",
      "Vercel",
    ],
    features: [
      "Course listings – digital literacy, cybersecurity, web dev, AI agent dev",
      "Business services – full‑stack apps, AI agents, chatbots",
      "Learning model – expert‑led, self‑paced, job‑ready skills",
      "Clear target audience (individuals, businesses, organisations)",
      "Tech‑forward, modern UI",
    ],
    sector: "EdTech",
  },
  {
    title: "DigiMagicTech - Computer Programming Educator",
    type: "Educational Website",
    description:
      "Educational website for DigiMagicTech, teaching computer programming and digital skills to primary and secondary school students and teachers in Kenya. Structured courses with age-appropriate content.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "shadcn/ui",
      "Vite",
      "Vercel",
    ],
    features: [
      "Age‑based courses (Primary – KES 15k, Secondary – KES 19.5k, Teachers – digital literacy)",
      "Expert team (professors of education, software engineering academics)",
      "Partners – Liberating Education (Germany), Matakiri Tumaini Trust, Ministry of Education",
      "Bright, engaging design for young learners",
      "Clear pricing and audience targeting",
    ],
    sector: "EdTech",
  },
  {
    title: "Gym Sable One - Fitness Landing Page",
    type: "Landing Page",
    description:
      "A sleek and modern fitness website showcasing gym programs, membership plans, and services with a responsive React-based interface and smooth animations.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "Vite",
      "Vercel",
    ],
    features: [
      "Hero section with strong call‑to‑action",
      "Program highlights (training options)",
      "Membership plans with pricing",
      "Fully responsive design",
      "Smooth Framer Motion animations",
    ],
    sector: "Fitness",
  },
  {
    title: "The Eleventh Hour - Coffee Shop Demo Site (UK)",
    type: "Landing Page",
    description:
      "Demo website for a UK-based coffee shop. Showcases menu items, shop ambiance, location, and contact details with a warm, inviting design – built as a modern frontend prototype.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "Vite",
      "Vercel",
    ],
    features: [
      "Hero section with menu call‑to‑action",
      "Categorised menu display (coffee, tea, food) with prices",
      "Photo gallery showcasing shop ambiance and products",
      "Location with Google Maps and opening hours",
      "Contact form for inquiries",
    ],
    sector: "Food & Beverage",
  },
  {
    title: "Matakiri Client Portal - Community Organisation Website",
    type: "Non-Profit Website",
    description:
      "Client-facing website for Matakiri, a community organisation. Showcases mission, community projects, impact stories, and ways to get involved (donate, volunteer, partner). Fully responsive and accessible.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "React Router DOM",
      "Vite",
      "Vercel",
    ],
    features: [
      "Mission & values communication",
      "Projects/initiatives timeline or cards",
      "Impact stories from beneficiaries",
      "Get involved sections (donate, volunteer, partner)",
      "Contact form with validation",
    ],
    sector: "Non-Profit",
  },
  {
    title: "Matakiri Admin Dashboard - Content Management System",
    type: "Dashboard",
    description:
      "Secure admin dashboard for Matakiri community organisation. Manage website content (projects, success stories, team bios) and view contact form submissions. Empowers non-technical staff to update the site.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "Chart.js / Recharts",
      "React Router DOM",
      "Vite",
      "Vercel",
    ],
    features: [
      "Authentication (JWT or session‑based)",
      "Manage projects, success stories, team members (CRUD)",
      "View contact form submissions with timestamps",
      "Analytics dashboard with charts (page views, submissions)",
      "Mobile‑responsive admin interface",
    ],
    sector: "Non-Profit / Tech",
  },
  {
    title: "Dantra Limited - FMCG Distributor Website",
    type: "Corporate Website",
    description:
      "Professional web platform for Dantra Limited, a leading FMCG distributor in Kenya. Showcases services, product categories, and brand partnerships with a sleek, mobile-first React interface.",
    tech: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Lucide Icons",
      "shadcn/ui",
      "Vite",
      "Vercel",
    ],
    features: [
      "Hero section with animated headline and CTA buttons",
      "Product category display (Beverages, Snacks, Personal Care, etc.)",
      "Services showcase for FMCG distribution capabilities",
      "Partnership inquiry via WhatsApp integration",
      "Click‑to‑call for quick communication",
      "Brand partners section",
    ],
    sector: "FMCG Distribution",
  },
  {
    title: "Sonar-Rock-vs-Mine-UI",
    type: "Machine Learning",
    description:
      "Advanced machine learning-powered web application that analyzes sonar signatures to classify underwater objects as mines or rocks. Features real-time classification, confidence scoring, and comprehensive data validation with a modern React interface.",
    tech: [
      "React",
      "Machine Learning",
      "Tailwind CSS",
      "Lucide Icons",
      "JavaScript",
    ],
    features: [
      "Real‑time classification (Mine vs Rock)",
      "Confidence scoring (70‑100%)",
      "Comprehensive input validation with user‑friendly errors",
      "Pre‑loaded sample data for testing",
      "One‑click clipboard integration for sample data",
      "Color‑coded results with visual feedback",
    ],
    sector: "Maritime / Defence",
  },
];